// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.891
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"bg-gray-800 mt-16\"><div class=\"max-w-7xl mx-auto px-4 py-12\"><div class=\"grid grid-cols-1 md:grid-cols-4 gap-8\"><div><h3 class=\"text-xl font-bold text-red-500 mb-4\">Shahid</h3><p class=\"text-gray-400\">Your ultimate destination for streaming entertainment.</p></div><div><h4 class=\"font-semibold mb-4\">Navigation</h4><ul class=\"space-y-2 text-gray-400\"><li><a href=\"/home\" class=\"hover:text-white transition\">Home</a></li><li><a href=\"/browse\" class=\"hover:text-white transition\">Browse</a></li><li><a href=\"/playlists\" class=\"hover:text-white transition\">Playlists</a></li></ul></div><div><h4 class=\"font-semibold mb-4\">Genres</h4><ul class=\"space-y-2 text-gray-400\"><li><a href=\"#\" class=\"hover:text-white transition\">Action</a></li><li><a href=\"#\" class=\"hover:text-white transition\">Comedy</a></li><li><a href=\"#\" class=\"hover:text-white transition\">Drama</a></li><li><a href=\"#\" class=\"hover:text-white transition\">Horror</a></li></ul></div><div><h4 class=\"font-semibold mb-4\">Support</h4><ul class=\"space-y-2 text-gray-400\"><li><a href=\"#\" class=\"hover:text-white transition\">Help Center</a></li><li><a href=\"#\" class=\"hover:text-white transition\">Contact Us</a></li><li><a href=\"#\" class=\"hover:text-white transition\">Privacy Policy</a></li><li><a href=\"#\" class=\"hover:text-white transition\">Terms of Service</a></li></ul></div></div><div class=\"border-t border-gray-700 mt-8 pt-8 text-center text-gray-400\"><p>&copy; 2024 Shahid. All rights reserved.</p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
